baseURL: "https://www.virtool.ca"
languageCode: "en-us"
title: "Virtool"
theme: "virtool"
staticDir: ["static"]

enableGitInfo: true
pygmentsCodeFences: true

sitemap:
  - filename: "sitemap.xml"

outputs:
  page:
    - "HTML"

menu:
  api:
    - Name: "Overview"
      Weight: 10
    - Name: "Endpoints"
      Weight: 20
  manual:
    - Name: "Getting Started"
      Weight: 10
    - Name: "Tutorials"
      Weight: 20
    - Name: "User Guide"
      Weight: 30
    - Name: "Science"
      Weight: 40
  developer:
    - Name: "Guide"
      Weight: 10
