baseURL = "/"
languageCode = "en-us"
title = "Virtool"
theme = "virtool"
staticDir = ["static"]

enableGitInfo = true
pygmentsCodeFences = true

[sitemap]
  filename = "sitemap.xml"

[outputs]
  home = ["HTML","Algolia"]
  page = ["HTML"]

[outputFormats.Algolia]
  baseName = "algolia"
  isPlainText = true
  mediaType = "application/json"
  notAlternative = true

[params.algolia]
  vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
  params = ["categories", "tags"]

[menu]
  [[menu.manual]]
    name = "Getting Started"
    description = "Installing and setting up Virtool for the first time."
    weight = 10
  [[menu.manual]]
    name = "Tutorials"
    description = "Recipes for doing core activities in Virtool."
    weight = 20

  [[menu.manual]]
    name = "User Guide"
    description = "Detailed documentation of all parts of Virtool comprehensive how-tos."
    weight = 30

  [[menu.manual]]
    name = "Science"
    description = "Explanations of the scientific and bioinformatic ideas behind Virtool."
    weight = 40

  [[menu.developer]]
    name = "API"
    description = "Documentation of the Virtool JSON API."
    weight = 10

  [[menu.developer]]
    name = "Contributing"
    description = "Resources for contributing to the Virtool project."
    weight = 20
